<style>
    .katerewards-enroll-login {
        border: 2px solid #00bfff;
        margin: 10px;
        padding: 10px;
        font-size: 14px;
    }
</style>

<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="katerewards-enroll-login">
        <div class="content">
            <input type="hidden" name="is_rewards_enrolled" value="1" id="is_rewards_enrolled" />
            <h2><?php echo $this->__('Already have a KateSomerville.com account?') ?></h2>
            <?php echo $this->__("If you already have a KateSomerville.com account, log in here to enroll in the rewards program") ?>
            <br>
            <br>
            <ul class="form-list">
                <li>
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                    </div>
                </li>
                <li>
                    <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        </div>
        <div class="buttons-set">
            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
            <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login & Enroll') ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('login-form', true);
    //]]>
</script>