<!-- Ajaxcart -->
<?php if(!$this->hasError()): ?>
<ul class="checkout-types">
	<li class="one-half">                            
		<?php if($this->getContinueShoppingUrl()): ?>
			<a href="#" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><?php echo $this->__('Continue Shopping') ?></a>
		<?php endif; ?>
	</li>   
<?php foreach ($this->getMethods('top_methods') as $method): ?>
	<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
	<li class="one-half"><?php echo $methodHtml; ?></li>
	<?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>