<script type="text/javascript">
	jQuery('#topCartLink').click(function () {
		jQuery('#topCartLink').css('pointer-events', 'none');
		jQuery('.close-btn').css('pointer-events', 'none');
		setTimeout(function () {
			jQuery('#topCartLink').css('pointer-events', '');
			jQuery('.close-btn').css('pointer-events', '');
		}, 1000);
	});
	jQuery('.close-btn').click(function () {
		jQuery('#topCartLink').css('pointer-events', 'none');
		jQuery('.close-btn').css('pointer-events', 'none');
		setTimeout(function () {
			jQuery('#topCartLink').css('pointer-events', '');
			jQuery('.close-btn').css('pointer-events', '');
		}, 1000);
	});
</script>