<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<?php if ($collection->getSize()) { ?>
    <div id="katereviews-main-display">
        <?php /* echo  $this->getPagerHtml();*/ ?>
        <?php $reviewcounter = 1; ?>
        <?php $customers = array(); ?>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $review) { ?>
            <div style="clear: both; padding: 0px;">
                <span style="color: #75b8db; margin-bottom:10px;">Your review of <?php echo $this->getProductName($review->getProductId()); ?></span>
				<div style="margin-bottom:10px; border-bottom: 1px solid #c8c8c8; clear: both;">        		
					<div class="first-line"><div class="rating-box"><div class="rating" style='<?php echo "width:" .  ($review->getStarRating())*20 . "%;"; ?>'></div></div></div>
					<div class="second-line"><div class="headline"><?php echo htmlentities($review->getReviewHeadline(), ENT_QUOTES, 'UTF-8') ?></div></div>
					<div class="comment">
						<?php if ($review->getReviewText()) { ?>
							<?php echo nl2br(htmlentities($review->getReviewText(), ENT_QUOTES, 'UTF-8')) ?>
						<?php } ?>
					</div>
					<div class="review-info">
						<?php echo "(Posted on " .  date('n/j/y',strtotime($review->getDate())) . ") Review by " . $review->fetchCustomerName(); ?>
					</div>
				<a style="line-height:30px; font-size:12px;" href="<?php echo $this->getProductUrl($review->getProductId()); ?>">View Product &raquo;</a>					
				</div>			
            </div>
            <?php $reviewcounter++; ?>
        <?php } ?>
        <?php /*  echo $this->getPagerHtml();*/ ?>
    </div>
<?php } else { ?>
    You haven't written any reviews.
<?php } ?>