<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>

<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
    </thead>
    <?php foreach($this->getItems() as $item): ?>
    <tr>
        <td class="name">	
            <?php echo $item->getName(); ?>
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
        </td>
        <td class="qty"><?php echo $item->getQty(); ?></td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
            <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
            <?php endif; ?>
        </td>
		
			
    </tr>
	<tr>
	<?php //Ordergroove Container  Module or cart ?>
	<?php
	$prod_id = "";
	$z_prod_options = array();
	$_product = $item->getProduct();
	$product = Mage::getModel('catalog/product')->load($_product->getId()); 
	
	if($product->getTypeId() == 'configurable'){
		$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null,$product); 
		$z_prod_options = Mage::helper('catalog/product_configuration')->getOptions($item);	
		
		foreach($childProducts as $child) {
				$x_prod_id 			= $child->getId();
				$mod_prod 			= Mage::getModel('catalog/product')->load($x_prod_id);
				$x_prod_attr_val 	= $product->getResource()->getAttribute('size')->getFrontend()->getValue($mod_prod);
				$x_prod_attr_shade 	= $product->getResource()->getAttribute('color_swatch')->getFrontend()->getValue($mod_prod);
					
				if( $x_prod_attr_val == $z_prod_options[0]['value'] ) $prod_id = $x_prod_id; 
				elseif( $x_prod_attr_shade == $z_prod_options[0]['value'] )	 $prod_id = $x_prod_id;
		}
	}else{
		$prod_id = $_product->getId();
	}
	?>
		<td class="og-summary" colspan=3>
			<div class="og-offer" data-og-module="or" data-og-product="<?php echo $prod_id; ?>"></div>
		</td>
		<?php //Ordergroove Container  Module or cart  ?>
		
		
	</tr>	
		
    <?php endforeach; ?>
</table>

<table class="onestepcheckout-totals">
    <?php foreach($this->getTotals() as $total): ?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
        ?>
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>
		<?php
		$code = $total->getCode();
		$value = $total->getValue();
		
		if($code == 'discount') {
			// Get redemption discount.
			$redemptionModel = Mage::getModel('alliance_fivehundredfriends/redemption');
			$redemptionModel->loadCurrentQuote();
			$redeemDiscount = -$redemptionModel->getTotalDiscount();
			
			if($redeemDiscount) {
				if($value == $redeemDiscount) $value = 0;
				else $value -= $redeemDiscount;
			}
		}
		?>
		<?php if($code != 'discount' || $value != 0) {?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">
            <?php
            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
            }
            elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
            }
            else    {
                $total_name = $total->getTitle();
            }

            echo $total_name;

            ?>
        </td>
        <td class="value">
            <?php echo $this->helper('checkout')->formatPrice($value); ?>
        </td>
    </tr>
		<?php }?>
		<?php if($code == 'discount' && $redeemDiscount) {?>
	<tr>
		<td class="title"><?php echo $this->__('Ultimate Kate Rewards'); ?></td>
		<td class="value"><?php echo $this->helper('checkout')->formatPrice($redeemDiscount);?></td>
    </tr>
		<?php }?>
    <?php endforeach; ?>
</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>