<script src="https://d3aa0ztdn3oibi.cloudfront.net/javascripts/ff.loyalty.widget.js" type="text/javascript"></script>

<?php

$uuid = $this->getUserId();
$load_args = $this->getArgs();

?>

<div class="page-title">
    <h1>My Rewards</h1>
</div>
<?php if(! Mage::helper('alliance_fivehundredfriends/data')->getCustomerRestriction()): ?> 
	<?php if(Mage::helper('alliance_fivehundredfriends/data')->currentCustomerEnrollmentStatus() == "Enrolled"): ?>
		<a href="<?php echo Mage::getUrl('rewards-program',array('_secure'=>true)); ?>" label="ukr-rewards">
			<img src="<?php echo $this->getSkinUrl('images/ukr-myrewards-banner.png', array('_secure'=>true)); ?>" label="ukr-rewards"/>
		</a>
	<?php endif; ?>
<iframe id='ff_member_iframe' style="width: 100%; scrolling='no'" frameBorder="0"></iframe>
<script type='text/javascript'>
    _ffLoyalty.initialize("<?php echo $uuid; ?>");
    _ffLoyalty.loadIframe(<?php echo $load_args; ?>);
</script>
<?php else: ?>
<div class="welcome-msg">
    <p>The Ultimate Kate Rewards program is restricted to only qualifying customers. Please contact customer care if you have additional questions <a href="<?php echo Mage::getBaseUrl();?>customer-care/">Customer Care</a>.</p>
</div>
<?php endif; ?>