<?php if ($this->isEnabled()): ?>
	<style>
		#email-capture-lightbox-container {
			position: fixed;
			top: 0;
			left: 0;
			right: 0;
			bottom: 0;
			padding: 0;
			margin: 0;
			width: 100%;
			height: 100%;
			background: rgba(0, 0, 0, 0.5);
			z-index: 999;
		}

		#email-capture-lightbox-signup {
			width: <?php echo $this->getSignupWidth(); ?>px;
			height: <?php echo $this->getSignupHeight(); ?>px;
			margin: auto;
			position: absolute;
			top: 0;
			left: 0;
			bottom: 0;
			right: 0;
			background-image: url('<?php echo $this->getSignupImageUrl(); ?>');
			background-size: <?php echo $this->getSignupWidth(); ?>px <?php echo $this->getSignupHeight(); ?>px;
		}

		#email-capture-lightbox-thankyou {
			width: <?php echo $this->getThankyouWidth(); ?>px;
			height: <?php echo $this->getThankyouHeight(); ?>px;
			margin: auto;
			position: absolute;
			top: 0;
			left: 0;
			bottom: 0;
			right: 0;
			background-image: url('<?php echo $this->getThankyouImageUrl(); ?>');
			background-size: <?php echo $this->getThankyouWidth(); ?>px <?php echo $this->getThankyouHeight(); ?>px;
		}

		.email-capture-close {
			height: 24px;
			position: absolute;
			top: 0;
			right: 0;
			color: white;
			background-color: #75b8db;
			width: 100%;
			float: right;
		}

		.email-capture-close span {
			float: right;
			border: 1px solid white;
			line-height: 14px;
			height: 14px;
			font-size: 13px;
			padding: 0 2px;
			margin: 4px 6px;			
		}

		.email-capture-close:after {
			content: "CLOSE";
			line-height: 26px;
			float: right;
			font-size: 13px;
		}
		
		.email-capture-error {
			width: 306px !important;
			height: 16px !important;
			position: absolute;
			bottom: 0px;
			right: 83px;
			font-size: 10px;
			line-height: 16px;
			color: #75b8db;
			text-align: center;
		}

		.email-capture-input {
			width: 163px !important;
			height: 30px !important;
			position: absolute;
			bottom: 18px;
			right: 163px;
			background-color: #fff;
		}

		.email-capture-submit {
			width: 115px !important;
			height: 32px !important;
			position: absolute;
			bottom: 18px;
			right: 30px;
			background-color: #75b8db !important;
			color: #fff;
			cursor: pointer;
			box-shadow:none !important;
			border:0;
		}

		.email-capture-continue {
			line-height: 32px;
			font-size: 16px;
			margin: 0 auto;
			cursor: pointer;
			color: white;
			background-color: #75b8db;
			text-align: center;
			position: absolute;
			bottom: 20px;
			right: 170px;
			padding: 0 10px;
		}

		.email-capture-continue:hover {
			text-decoration: none;
			color:white !important;
		}	

		.email-capture-coupon-code {
			position: absolute;
			bottom: 132px;
			right: 137px;
			font-size: 14px;
			color: #FFF;
			background-color: orange;
			width: 100px;
			text-align: center;
			height: 20px;
			line-height: 20px;
		}

		.email-capture-disclaimer {
			position: absolute;
			bottom: 74px;
			right: 50px;
			width: 295px;
			font-size: 11px;
			color: gray;			
		}
		
	</style>

	<div id="email-capture-lightbox-container" style="display: none;">
		<div id="email-capture-lightbox-signup">
			<div class="email-capture-close"><span>X</span></div>
			<div class="email-capture-error">Please enter a valid email address and try again.</div>
			<input class="email-capture-ele email-capture-input" type="email" name="email" autocomplete="off" placeholder="Email Address">
			<button class="email-capture-ele email-capture-submit" type="submit">Submit</button>
		</div>
		<div id="email-capture-lightbox-thankyou">
			<div class="email-capture-close"><span>X</span></div>
			<div class="thankyou-bottom">
				<span>
					<a class="email-capture-continue" href="<?php echo $this->getThankyouLinkUrl(); ?>"><?php echo $this->getThankyouLinkText(); ?></a>
				</span>
				<br>
			</div>
			<div class="email-capture-coupon-code"><?php echo $this->getThankyouCouponCode(); ?></div>
			<div class="email-capture-disclaimer"><?php echo $this->getThankyouDisclaimerText(); ?></div>
		</div>
	</div>
	<script src="/js/jquery-cookie/jquery.cookie.js"></script>
	<script type="text/javascript">
		var emailCaptureError = function () {
			jQuery('.email-capture-ele').removeAttr('disabled');
			jQuery('.email-capture-error').show();
			jQuery('.email-capture-input').select();
		}
		var emailCaptureSuccess = function () {
			jQuery('#email-capture-lightbox-signup').hide();
			jQuery('#email-capture-lightbox-thankyou').show();
		}
		var emailCaptureSubmit = function () {
			jQuery('.email-capture-error').hide();
			jQuery('.email-capture-ele').attr('disabled', 'disabled');
			jQuery.ajax({
				url: '/emailcapture/ajax/subscribe',
				type: 'post',
				dataType: 'json',
				data: {'email': jQuery('.email-capture-input').val()}
			}).done(function (data) {
				if (data.status == 'error') {
					emailCaptureError();

				} else if (data.status == 'success') {
					emailCaptureSuccess();
				}
			}).fail(function (data) {
				emailCaptureError();
			});
		}
		jQuery(document).ready(function () {
			if (jQuery.cookie('alliance_emailcapture_shown') !== 'true') {
				jQuery.cookie('alliance_emailcapture_shown', 'true', { path: '/', expires: 3650, domain: '<?php echo Mage::helper('alliance_emailcapture')->getCookieDomain(); ?>' });
				jQuery('#email-capture-lightbox-container').show();
				jQuery('.email-capture-input').focus();
			}
			jQuery('#email-capture-lightbox-thankyou').hide();
			jQuery('.email-capture-error').hide();
			jQuery('.email-capture-close').click(function () {
				jQuery('#email-capture-lightbox-container').hide();
			});
			jQuery('.email-capture-continue').click(function () {
				jQuery('#email-capture-lightbox-container').hide();
			});
			jQuery('#email-capture-lightbox-container').click(function () {
				jQuery(this).hide();
			});
			jQuery('#email-capture-lightbox-signup').click(function (event) {
				event.stopPropagation();
			});
			jQuery('#email-capture-lightbox-thankyou').click(function (event) {
				event.stopPropagation();
			});
			jQuery('.email-capture-submit').click(emailCaptureSubmit);
			jQuery('.email-capture-input').bind('keypress', function (event) {
				if (event.which == 13) {
					emailCaptureSubmit();
				}
			});
		});
	</script>
<?php endif; ?>
