<?php
$imageUrl = $this->getSkinUrl('images/sweepstakes/');
?>
<div id="sweepstakes-container">
	<div id="sweepstakes-header">
		<div id="sweepstakes-logo"><img src="<?php echo $imageUrl?>katesomerville-byrdie.png" alt="Kate Somerville + Bridge"/></div>
		<div id="sweepstakes-title-before">Enter to win an</div>
		<h1>Escape to<br/>Hollywood</h1>
		<p>Where Age Is Just A Number</p>
	</div>
	<div id="sweepstakes-content">
		<p class="main-text">To celebrate Kate’s 10th anniversary, <strong>Kate Somerville Skincare</strong> &amp; <strong>Byrdie</strong><br/>
		invite you to <strong>enter for a chance to win</strong> the ultimate trip for 2 to Hollywood<br/>
		to be pampered like a star.</p>
		
		<div id="sweepstakes-details"><div id="sweepstakes-details-inner">
			<div class="left">
				<h2>One lucky winner will receive:</h2>
				<ul>
					<li><em>2 round trip tickets</em> to sunny Los Angeles</li>
					<li>2 night stay in West Hollywood at<br/>the <strong>Petit Ermitage Hotel</strong></li>
					<li>2 DermalQuench&trade; Oxygen Facials at the<br/><em>Kate Somerville Skin Health Experts Clinic</em></li>
					<li>A customized skincare regimen with<br/><em>$1000 worth of Kate Somerville products</em></li>
					<li>Dinner for 2 at celebrity hotspot, <em>Fig &amp; Olive</em></li>
					<li>2 glamorous blowouts at <em>Frederic Fekkai Salon</em></li>
					<li><em>$300</em> meal &amp; transportation credit</li>
				</ul>
				<p class="sweepstakes-highlight"><strong>More than $4,000 value!</strong></p>
			</div>
			<div class="right">
				<div id="sweepstakes-katelogos">
					<img src="<?php echo $imageUrl;?>logo.png" alt="Kate Somerville"/>
					<img src="<?php echo $imageUrl?>celebrating-10years.png" alt="Celebrating 10 Years"/>
				</div>
				<div id="sweepstakes-embebedform">
					<iframe id="JotFormIFrame" onload="window.parent.scrollTo(0,0)" allowtransparency="true" src="http://form.jotform.us/form/50355670906154" frameborder="0"  style="width:100%; height:300px; border:none;" scrolling="no"></iframe>
					<script type="text/javascript">window.handleIFrameMessage = function(e) {var args = e.data.split(":");var iframe = document.getElementById("JotFormIFrame");if (!iframe)return;switch (args[0]) {case "scrollIntoView":iframe.scrollIntoView();break;case "setHeight":iframe.style.height = args[1] + "px";break;case "collapseErrorPage":if (iframe.clientHeight > window.innerHeight) {iframe.style.height = window.innerHeight + "px";}break;case "reloadPage":window.location.reload();break;}};if (window.addEventListener) {window.addEventListener("message", handleIFrameMessage, false);} else if (window.attachEvent) {window.attachEvent("onmessage", handleIFrameMessage);}</script>
				</div>
				<p class="official-rules">by clicking “Enter to Win” you agree to the <a href="/sweepstakesrules" target="_blank">Official Rules</a></p>
			</div>
		</div></div>
		
		<div id="sweepstakes-images">
			<div class="sweepstakes-images-left">
				<img src="<?php echo $imageUrl?>fig-olive.jpg" alt="Fig &amp; Olive"/>
				<img src="<?php echo $imageUrl?>ermitage-hotel.jpg" alt="Petit Ermitage Hotel"/>
			</div>
			<div class="sweepstakes-images-center">
				<img src="<?php echo $imageUrl?>skin-health-experts-clinic.jpg" alt="Kate Somerville Skin Health Experts Clinic"/>
			</div>
			<div class="sweepstakes-images-right">
				<img src="<?php echo $imageUrl?>frederic-fekkai.jpg" alt="Frederic Fekkai Salon"/>
				<img src="<?php echo $imageUrl?>melrose-place.jpg" alt="Melrose Place"/>
			</div>
		</div>
		
		<div id="sweepstakes-partners">
			<div class="left">
				<h3>Sponsored By:</h3>
				<ul id="sweepstakes-partners-logos">
					<li><img src="<?php echo $imageUrl?>logo-fig-olive.png" alt="Fig &amp; Olive"/></li>
					<li><img src="<?php echo $imageUrl?>logo-frederic-fekkai.png" alt="Frederic Fekkai Salon"/></li>
					<li><img src="<?php echo $imageUrl?>logo-ermitage-hotel.png" alt="Petit Ermitage Hotel"/></li>
				</ul>
			</div><div class="right">
				<h3>Benefiting:</h3>
				<ul id="sweepstakes-partners-logos">
					<li><img src="<?php echo $imageUrl?>logo-art-elisum.png" alt="The Art of Elisum"/></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div id="sweepstakes-footer">
	<p>No purchase necessary to enter. Void where prohibited. Open to all legal residents of the 50 contiguous United States and the District of Columbia who are 21 or older at the time of entry.
	Giveaway begins at 12:01 AM ET on 2/18/2015 and ends at 11:59 PM EST on 2/27/2015</p>
</div>