<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>

        <?php else: ?>
            <?php // Grid Mode ?>
            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = 2; ?>
            <?php $i = 0; ?>
            <?php foreach ($_productCollection as $_product): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
            <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="product-image">
                    <a href="<?php echo $_product->getProductUrl() ?>" rel="external" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                </div>
                <div class="product-header" >
                    <a href="<?php echo $_product->getProductUrl() ?>" rel="external" title="<?php echo $this->stripTags($_product->getResource()->getAttribute('title')->getFrontend()->getValue($_product), null, true) ?>">
                        <h2 class="product-name" id="product-link<?= $_product->getEntityId() ?>"><?php echo $_product->getResource()->getAttribute('title')->getFrontend()->getValue($_product); ?></h2>
                        <?php if ($_product->getResource()->getAttribute('sub_title')->getFrontend()->getValue($_product)): ?>
                            <h5 class="product-subtitle" id="subtitle-<?= $_product->getEntityId() ?>"><?php echo $_product->getResource()->getAttribute('sub_title')->getFrontend()->getValue($_product); ?></h5>
                        <?php endif; ?>

                    </a>
                </div>

                <?php if($_product->getRatingSummary()): ?>
                    <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
            </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
        <?php endif ?>

        <?php endforeach ?>

            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>

    </div>

<?php endif; ?>