<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$_product_id = $this->getProductId();
$_category_id = $this->getCategoryId();

$_product = Mage::getModel('catalog/product')->load($_product_id);
$_category = Mage::getModel('catalog/category')->load($_category_id);

$udo = array(
            page_name => $_product->getName(),
            page_type => "product send",
            product_id => $_product->getId(),
            product_sku => $_product->getSku(),
            product_name => $_product->getName(),
            product_brand => $_product->getBrand(),
            product_category => $_category ? $_category->getName() : 'no_category',
            product_unit_price => number_format($_product->getSpecialPrice()?:"",2,""),
            product_list_price => number_format($_product->getPrice()?:"",2,"")
);


$tealium = $helper->getTealiumObject($store, $this);
$tealium->pageType("ProductPage");
$tealium->updateUdo($udo);
echo $tealium->render("udo");
echo $helper->getDiagnosticTag($store);
?>