<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$tealium = $helper->getTealiumObject($store, $this);
$tealium->pageType("Search");
$tealium->updateUdo("page_type", "tag product list");
$tealium->updateUdo("page_name", $this->getLayout()->getBlock('head')->getTitle());
echo $tealium->render("udo");
echo $helper->getDiagnosticTag($store);
?>