<?php
$_item = $this->getItem();
$_itemId = $_item->getId();

$ajaxcartHelper = Mage::helper('ajaxcart');
$isFreeSample = $ajaxcartHelper->checkFreesample($this->getProduct());
?>
<?php $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM); ?>
<li class="item" id="ajaxcart-<?php echo $_itemId;?>" data-productid="<?php echo $this->getProduct()->getId();?>" data-freesample="<?php echo $isFreeSample?>">
<?php if ($this->hasProductUrl()): ?>
    <a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>"
       class="product-image"><img
            src="<?php echo $this->getProductThumbnail()->resize(50)->setWatermarkSize('30x10'); ?>"
            alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/></a>
<?php else: ?>
    <span class="product-image">
            <img src="<?php echo $this->getProductThumbnail()->resize(50)->setWatermarkSize('30x10'); ?>"
                 alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"
                 title="<?php echo $this->escapeHtml($this->getProductName()) ?>"/>
        </span>
<?php endif; ?>

<div class="product-details">
    <p class="product-name">
        <?php if ($this->hasProductUrl()): ?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->escapeHtml($this->getProductName()) ?>
        <?php endif; ?>
    </p>
    <table cellpadding="0">

        <?php if ($canApplyMsrp): ?>

            <tr>
                <th><?php echo $this->__('Price'); ?></th>
                <td><span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span></td>
            </tr>

        <?php else: ?>

            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <th><?php echo $this->__('Excl. Tax'); ?></th>
                    <?php else: ?>
                        <th><?php echo $this->__('Price'); ?></th>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                        <td><?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?></td>
                    <?php else: ?>
                        <td><?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?></td>
                    <?php endif; ?>
                </tr>

                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>

                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <tr>
                                <th>
                                    <small><?php echo $tax['title']; ?>:</small>
                                </th>
                                <td>
                                    <small><?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>

                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <tr>
                                <th>
                                    <small><?php echo $tax['title']; ?></small>
                                </th>
                                <td>
                                    <small><?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>

                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <tr>
                                <th>
                                    <small><?php echo $tax['title']; ?></small>
                                </th>
                                <td>
                                    <small><?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>

                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                        <tr>
                            <th>
                                <small><?php echo Mage::helper('weee')->__('Total:'); ?></small>
                            </th>
                            <td>
                                <small><?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?></small>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>



            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                <tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <th><?php echo $this->__('Incl. Tax'); ?></th>
                    <?php else: ?>
                        <th><?php echo $this->__('Price'); ?></th>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                        <td><?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></td>
                    <?php else: ?>
                        <td><?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?></td>
                    <?php endif; ?>
                </tr>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <tr>
                                <th>
                                    <small><?php echo $tax['title']; ?></small>
                                </th>
                                <td>
                                    <small><?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <tr>
                                <th>
                                    <small><?php echo $tax['title']; ?></small>
                                </th>
                                <td>
                                    <small><?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <tr>
                                <th>
                                    <small><?php echo $tax['title']; ?></small>
                                </th>
                                <td>
                                    <small><?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                        <tr>
                            <th>
                                <small><?php echo Mage::helper('weee')->__('Total incl. tax'); ?></small>
                            </th>
                            <td>
                                <small><?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></small>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>

        <?php endif; //Can apply MSRP ?>
        <tr>
            <th><?php echo $this->__('Qty'); ?></th>
            <td class="cart-item-qty"><?php echo $this->getQty() ?></td>
        </tr>
    </table>
    <?php if ($_options = $ajaxcartHelper->getItemOptions($_itemId)): ?>
        <div class="truncated">
            <div class="truncated_full_value">
                <div class="item-options">
                    <p><?php echo $this->__('Options Details'); ?></p>
                    <dl>
                        <?php foreach ($_options as $attributeId => $_option) : ?>
                            <dt class="item-options-data" data-id="<?php echo $attributeId?>" data-label="<?php echo $_option['label'];?>" data-value="<?php echo $_option['value'];?>" data-text="<?php echo $_option['text'];?>"><?php echo $_option['label']?></dt>
                            <dd><?php echo $_option['text'];?></dd>
                        <?php endforeach; ?>
                    </dl>
                </div>
            </div>
            <a href="#" onclick="return false;" class="details"><?php echo $this->__('View Details') ?></a>
        </div>
    <?php endif; ?>
    <?php if ($_item->getProduct()->isVisibleInSiteVisibility() && ! $isFreeSample): ?>
     <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item') ?>" class="btn-edit"><?php echo $this->__('Edit item') ?></a>
	<span>|</span>
    <?php endif ?>
    <a href="<?php echo $this->getDeleteUrl() ?>" data-product="<?php echo $this->getProduct()->getId();?>" title="<?php echo $this->__('Remove item') ?>" class="btn-remove"><?php echo $this->__('Remove item') ?></a>
</div>
</li>