<!-- Ajaxcart -->
<?php if(!$this->hasError()): ?>
<?php if($this->getContinueShoppingUrl()): ?>
<div class="continue"><a href="<?php echo $this->getContinueShoppingUrl() ?>"><?php echo $this->__('Continue Shopping') ?></a></div>
<?php endif; ?>

<ul class="checkout-types">
<?php foreach ($this->getMethods('methods') as $method): ?>
	<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
	<li><?php echo $methodHtml; ?></li>
	<?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>