<div class="giveawayfb-container">
	<div class="giveawayfb-title"><img src="<?php echo $this->getSkinUrl('images/giveawayfb/landing-title.png');?>" width="440" height="165" alt="Discover Hollywood's Best Kept Secret"/></div>
	<div class="giveawayfb-landing">
		<form id="frmCustomerVerification" action="<?php echo $this->getCustomerVerificationAction();?>" method="post">
		<fieldset>
		
<p>
Thank you for your interest in trying Kate Somerville Skincare! <br/><br/>
Due to popular demand we have reached the limit of the sample kits available. We have temporarily paused this offer while we work to build additional samples. Please check back at a later date. <br/> <br/>
In the meantime, you may sign up for our <a href="/newsletter/" class="text" target="_blank">newsletter</a> to receive exclusive offers, tips and more. <br/><br/>
KateSomerville.com always offers you a choice of 3 Free Samples with every purchase. <br/><br/>
Wishing you Complexion Perfection. 
</p>
		<?php 
		/*
		<p>Sign up now for a set of free samples. Pick from several customized skincare regimens to achieve a healthy, glowing complexion.</p>
		<input type="text" id="customer-verification-email" name="email" placeholder="ENTER EMAIL ADDRESS" class="required-entry validate-email"/><br/>
		<a href="/privacy-policy/" target="_blank">Privacy Policy</a> <button id="customer-verification-submit" class="giveawayfb-button">Sign up</button>
		
		*/
		?>
		</fieldset>
		</form>
	</div>
	<script type="text/javascript">
	//< ![CDATA[
	  var frmVerification= new VarienForm('frmCustomerVerification', true);
	//]]>
	</script>
</div>
