<div id="katereviews-main-display">
    <div class="page-title"><h1>My Product Reviews</h1></div>
        
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<?php if ($collection->getSize()) { ?>


        <?php echo $this->getPagerHtml(); ?>
        <?php $reviewcounter = 1; ?>
        <?php $customers = array(); ?>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $review) { ?>
            <div class="review-info">
                <p><em>Your review of <?php echo $this->getProductName($review->getProductId()); ?></em></p>
                
                <?php
					$avg = $review->getStarRating(); 
					$avgWidth = $avg/5;
					$percent = round((float)$avgWidth * 100 ) . '%';
				?>
				<div class="rating-box">
			    	<div class="rating" style="width:<?php echo $percent; ?>"></div>
			    </div>
    
    
                <h2><?php echo htmlentities($review->getReviewHeadline(), ENT_QUOTES, 'UTF-8') ?></h2>
                <?php if ($review->getReviewText()) { ?>

                    <?php echo nl2br(htmlentities($review->getReviewText())) ?>

                <?php } ?>
                
                <?php echo $this->getTopContributorText($review->getCustomerId()) ?>
				
				<br /><br />
                <p>Date: <?php echo date("m/d/Y", strtotime($review->getDate())); ?><br />
                Review Status: <?php echo $review->getStatus(); ?></p>

                <a href="<?php echo $this->getProductUrl($review->getProductId()); ?>">View Product</a>
            </div>
            <?php $reviewcounter++; ?>
        <?php } ?>
        <?php echo $this->getPagerHtml(); ?>
   
<?php } else { ?>
    
    <p>You haven't written any reviews.</p>
    
<?php } ?>
</div>