<div id="katereviews-preview-form">

	<div class="first-line">
		<div class="rating-box">
			<div class="rating" style='<?php echo "width:" . ($this->postData['review-stars']) * 20 . "%;"; ?>'></div>
		</div>
		<div class="headline"><?php echo htmlentities($this->postData['review-headline'], ENT_QUOTES, 'UTF-8') ?></div>
	</div>
	<div class="comment">
		<?php echo htmlentities($this->postData['review-comments'], ENT_QUOTES, 'UTF-8'); ?>
	</div>

	<div class="preview-buttons">
		<form id="katereviews-save-form" class="left" action="<?php echo Mage::getUrl('katereviews/submit/save'); ?>" method="POST">
			<input type="hidden" name="review-product-id" value="<?php echo $this->product_id ?>">
			<input type="hidden" name="review-customer-id" value="<?php echo $this->customer_id ?>">
			<input type="hidden" name="review-stars" value="<?php echo $this->postData['review-stars'] ?>">
			<input type="hidden" name="review-recommended" value="<?php echo $this->postData['review-recommended'] ?>">
			<input type="hidden" name="review-headline" value="<?php echo htmlentities($this->postData['review-headline'], ENT_QUOTES, 'UTF-8') ?>">
			<input type="hidden" name="review-comments" value="<?php echo htmlentities($this->postData['review-comments'], ENT_QUOTES, 'UTF-8') ?>">
			<input type="hidden" name="review-purchase-location" value="<?php echo $this->postData['review-purchase-location'] ?>">
			<input type="hidden" name="review-skin-concern" value="<?php echo $this->postData['review-skin-concern'] ?>">
			<input type="hidden" name="review-age-range" value="<?php echo $this->postData['review-age-range'] ?>">
			<input type="hidden" name="review-long-owned" value="<?php echo $this->postData['review-long-owned'] ?>">
			<input type="hidden" name="review-how-often" value="<?php echo $this->postData['review-how-often'] ?>">
			<input type="hidden" name="review-rewards-member" value="<?php echo $this->postData['review-rewards-member'] ?>">
			<input type="hidden" name="review-city-state" value="<?php echo $this->postData['review-city-state'] ?>">
			<input type="hidden" name="review-notify" value="<?php echo $this->postData['review-notify'] ?>">
			<input id="katereviews-save-button" class="button left-button" type="submit" value="Save">
		</form>
		<form class="right" action="<?php echo Mage::getUrl('katereviews/write/index/id/' . $this->postData['review-product-id']); ?>" method="POST">
			<input type="hidden" name="review-product-id" value="<?php echo $this->product_id ?>">
			<input type="hidden" name="review-customer-id" value="<?php echo $this->customer_id ?>">
			<input type="hidden" name="review-stars" value="<?php echo $this->postData['review-stars'] ?>">
			<input type="hidden" name="review-recommended" value="<?php echo $this->postData['review-recommended'] ?>">
			<input type="hidden" name="review-headline" value="<?php echo htmlentities($this->postData['review-headline'], ENT_QUOTES, 'UTF-8') ?>">
			<input type="hidden" name="review-comments" value="<?php echo htmlentities($this->postData['review-comments'], ENT_QUOTES, 'UTF-8') ?>">
			<input type="hidden" name="review-purchase-location" value="<?php echo $this->postData['review-purchase-location'] ?>">
			<input type="hidden" name="review-skin-concern" value="<?php echo $this->postData['review-skin-concern'] ?>">
			<input type="hidden" name="review-age-range" value="<?php echo $this->postData['review-age-range'] ?>">
			<input type="hidden" name="review-long-owned" value="<?php echo $this->postData['review-long-owned'] ?>">
			<input type="hidden" name="review-how-often" value="<?php echo $this->postData['review-how-often'] ?>">
			<input type="hidden" name="review-rewards-member" value="<?php echo $this->postData['review-rewards-member'] ?>">
			<input type="hidden" name="review-city-state" value="<?php echo $this->postData['review-city-state'] ?>">
			<input type="hidden" name="review-notify" value="<?php echo $this->postData['review-notify'] ?>">
			<input class="button right-button" type="submit" value="Edit">
		</form>
	</div>
</div>
<script type="text/javascript">
	jQuery('#katereviews-save-form').submit(function () {
		jQuery('#katereviews-save-button').attr('disabled', true);
	});
</script>