<div id="katereviews-success-page" class="success-review-description">

    <div class="page-title"><h1>Thank you</h1></div>
	<p style="font-size:13px; color:#6a747c; margin:16px; ">Thank you for your submitting your review. Kate Somerville respects and values our clients opinions and appreciate your taking the time to share yours.</p>

	<div class="description" style="margin:16px; font-weight:normal !important;">
		Please allow 3 to 5 business days for your review to appear online. Please note that submissions are subject to the terms of our <div style="display:inline;" class="review-guideline-tooltip-container success-review-guideline">
			<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)."review-guidelines"; ?>"><span style="color:#5eb0e5;">Review Guidelines</span></a><span>.</span>
	</div>
    <br/>
    <a style="font-weight:normal !important; margin-top:20px;" div class="button" href="<?php echo $this->product_url; ?>"><span><span>Back to Product</span></span></a>
    <br />
    <a  class="button" href="<?php echo Mage::app()->getStore($storeId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>"><span><span>Continue Shopping</span></span></a>
    <br/>
	
</div>