<div class="container">
<p class="description">Join UltimateKate to earn points<br/>when you shop and redeem them<br/>for beauty rewards & gifts.</p>
<h2>You could earn <?php echo $this->getPotentiallyPoints();?> points on<br/>your purchase today.</h2>
<a class="claim-points" href="<?php echo Mage::getUrl('katerewards/enroll/now');?>">Claim your points &gt;</a>
<p class="desclaimer">Purchase points are pending for 30 days.</p>
</div>
<?php
// Check if we need to active Reward tab.
if(Mage::getSingleton('core/session')->getLoadRewardTab()) {
?>
<script type="text/javascript">
Event.observe(window, 'load', function() {
	setTimeout(function() {
		collateralTabs.activeTab = $('reward-tab');
		collateralTabs.select();
	}, 500);
});
</script>
<?php
	Mage::getSingleton('core/session')->unsLoadRewardTab();
}
?>