</div>
<div id="katereviews-main-display">
    <?php if ($this->total_count > 0) { ?>
        <div class="button top-reviews"><a href="<?php echo Mage::getUrl('katereviews/write/index/id/'.$this->product_id); ?>">Write Review</a></div>
    <?php } else { ?>
        <div class="button top-reviews"><a href="<?php echo Mage::getUrl('katereviews/write/index/id/'.$this->product_id); ?>">First to Review</a></div>
    <?php } ?>
    <?php if ($this->total_count > 4) { ?>
        <div class="button top-reviews"><a href="<?php echo Mage::getUrl('katereviews/view/index/id/'.$this->product_id); ?>">See All <?php echo $this->total_count ?> Reviews</a></div>
    <?php } ?>
	
    <?php $reviewcounter = 0; ?>
    <?php foreach ($this->_collection as $review) { ?>
        <?php if ($reviewcounter === 5) break; ?>
            <?php $helpful = $this->getHelpfuls($review->getId()); ?>
            <div style="margin-bottom:10px; border-top: 1px solid #c8c8c8; clear: both; ">        		
				<div class="first-line"><div class="rating-box"><div class="rating" style='<?php echo "width:" .  ($review->getStarRating())*20 . "%;"; ?>'></div></div></div>
				<div class="second-line"><div class="headline"><?php echo htmlentities($review->getReviewHeadline(), ENT_QUOTES, 'UTF-8') ?></div></div>
				<div class="comment">
					<?php if ($review->getReviewText()) { ?>
						<?php echo nl2br(htmlentities($review->getReviewText(), ENT_QUOTES, 'UTF-8')) ?>
					<?php } ?>
				</div>
				<div class="review-info">
					<?php echo "(Posted on " .  date('n/j/y',strtotime($review->getDate())) . ") Review by " . $review->fetchCustomerName(); ?>
				</div>		
            </div>
            <?php $reviewcounter++; ?>
    <?php } ?>
</div>
<script>
    <?php $reviewcounter = 0; ?>
    <?php foreach ($this->_collection as $review) { ?>
    <?php if ($reviewcounter === 5) break; ?>
        jQuery('#Helpful-Yes-AJAX-<?php echo $reviewcounter; ?>').click(function() {
            jQuery.ajax({
                url: '/katereviews/submit/helpyes/customerid/<?php echo $this->customer_id; ?>/reviewid/<?php echo $review->getId(); ?>'
            });
            jQuery('#found-review-helpful-input-<?php echo $reviewcounter; ?>').hide();
            jQuery('#found-review-helpful-<?php echo $reviewcounter; ?>').show();
        });

        jQuery('#Helpful-No-AJAX-<?php echo $reviewcounter; ?>').click(function() {
            jQuery.ajax({
                url: '/katereviews/submit/helpno/customerid/<?php echo $this->customer_id; ?>/reviewid/<?php echo $review->getId(); ?>'
            });
            jQuery('#found-review-helpful-input-<?php echo $reviewcounter; ?>').hide();
            jQuery('#found-review-unhelpful-<?php echo $reviewcounter; ?>').show();
        });
        <?php $reviewcounter++; ?>
    <?php } ?>
</script>