<script src="https://d3aa0ztdn3oibi.cloudfront.net/javascripts/ff.loyalty.widget.js" type="text/javascript"></script>

<?php

$uuid = $this->getUserId();
$load_args = $this->getArgs();

?>

<div class="page-title">
    <h1>My Rewards</h1>
</div>
<iframe id='ff_member_iframe' style="width: 100%; scrolling='no'" frameBorder="0"></iframe>
<script type='text/javascript'>
    _ffLoyalty.initialize("<?php echo $uuid; ?>");
    _ffLoyalty.loadIframe(<?php echo $load_args; ?>);
</script>