<?php /* $_product = $this->getProduct(); ?>
<!-- Put this script tag anywhere in body. -->
<script type="text/javascript">_ffLoyalty.displaySurpriseWidget("<?php echo Mage::helper('alliance_fivehundredfriends')->getSurprisedelightWidgetId();?>");</script>
<!-- Log events to the widget by either:  -->
<!-- 1. When the page loads  -->
<script type="text/javascript">_ffLoyalty.logSurpriseEvent("product_view", "<?php echo $_product->getId() ?>");</script>
*/?>	