<!-- end temporary styles -->
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<?php if ($collection->getSize()) { ?>
    <div id="katereviews-main-display">
        <div class="page-title"><h1>Customer Reviews</h1></div>
        <p>Customer Reviews for <?php echo $this->product_name; ?></p>

        <div class="right">
            <?php if ($this->review_count > 0) { ?>
                <a class="button" href="<?php echo Mage::getUrl('katereviews/write/index/id/'.$this->product_id); ?>"><span><span>Write your Review</span></span></a>
            <?php } else { ?>
                <a class="button" href="<?php echo Mage::getUrl('katereviews/write/index/id/'.$this->product_id); ?>"><span><span>Be the first to review this product</span></span></a>
            <?php } ?>
        </div>
		<br/>
        <a class="button" href="<?php echo $this->getBackUrl(); ?>">Back to Product</a>

        <?php $reviewcounter = 1; ?>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $review) { ?>
            <?php $helpful = $this->getHelpfuls($review->getId()); ?>
                <div style="padding: 10px 16px 0 16px; clear: both; ">
                    <div class="first-line"><div class="rating-box"><div class="rating" style='<?php echo "width:" .  ($review->getStarRating())*20 . "%;"; ?>'></div></div></div>
                    <div class="second-line"><div class="headline"><?php echo htmlentities($review->getReviewHeadline(), ENT_QUOTES, 'UTF-8') ?></div></div>
                    <div class="comment">
                        <?php if ($review->getReviewText()) { ?>
                            <?php echo nl2br(htmlentities($review->getReviewText(), ENT_QUOTES, 'UTF-8')) ?>
                        <?php } ?>
                    </div>
                    <div class="review-info" style="padding-bottom:10px; border-bottom:1px solid #c8c8c8;">
                        <?php echo "(Posted on " .  date('n/j/y',strtotime($review->getDate())) . ") Review by " . $review->fetchCustomerName(); ?>
                    </div>
                </div>
            <?php $reviewcounter++; ?>
        <?php } ?>
        <br clear="all" />
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <script>
        <?php $reviewcounter = 1; ?>
        <?php foreach ($this->_collection as $review) { ?>
        jQuery('#Helpful-Yes-AJAX-<?php echo $reviewcounter; ?>').click(function() {
            jQuery.ajax({
                url: '/katereviews/submit/helpyes/customerid/<?php echo $this->customer_id; ?>/reviewid/<?php echo $review->getId(); ?>'
            });
            jQuery('#found-review-helpful-input-<?php echo $reviewcounter; ?>').hide();
            jQuery('#found-review-helpful-<?php echo $reviewcounter; ?>').show();
        });

        jQuery('#Helpful-No-AJAX-<?php echo $reviewcounter; ?>').click(function() {
            jQuery.ajax({
                url: '/katereviews/submit/helpno/customerid/<?php echo $this->customer_id; ?>/reviewid/<?php echo $review->getId(); ?>'
            });
            jQuery('#found-review-helpful-input-<?php echo $reviewcounter; ?>').hide();
            jQuery('#found-review-unhelpful-<?php echo $reviewcounter; ?>').show();
        });
        <?php $reviewcounter++; ?>
        <?php } ?>
    </script>
<?php } else { ?>
    No reviews found.
<?php } ?>