<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php // echo $this->getToolbarHtml() ?>
    <?php echo $this->getAdditionalHtml() ?>
    <div class="category-products">
        <?php // Grid Mode ?>
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i == 3 && !$spotlit) { ?>
            <!-- BEGIN PRODUCT SPOTLIGHT HTML -->
            <ul class="products-grid product-spotlight">
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="prod-grid-thumb">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(525); ?>" width="525" height="525" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                        <div class="prod-grid-content">
                            <div class="prod-grid-content-inner actions">

                                <div class="button btn-view"><a class="button" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span><span><?php echo $this->__('View Detail') ?></span></span></a></div>

                                <div class="button btn-quickview"><a class="button fancybox" data-fancybox-type="iframe" href="<?php echo Mage::getUrl('quickview/product/view/id/' . $_product->getId()); ?>"><span><span><?php echo $this->__('Quick View') ?></span></span></a></div>
                                <?php if($_product->isSaleable()): ?>
                                    <div class="qty-holder">
                                        <span><?php echo $this->__('Qty'); ?><?php echo $this->getMinimalQty($_product) ?></span>
                                        <?php
                                        $_max = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getMaxSaleQty();
                                        ?>
                                        <script type="text/javascript">
                                            function setQty(id, url) {
                                                var qty = document.getElementById('qty_' + id).value;
                                                if (url.substring(url.length-1) == '/') {
                                                    document.getElementById('cart_button_' + id).innerHTML = '<button type="button" class="button" onclick="setLocation(\'' + url + 'qty/' + qty + '/\')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button>';
                                                }
                                            }
                                        </script>
                                        <select name="qty_<?php echo $_product->getId() ?>" id="qty_<?php echo $_product->getId() ?>" maxlength="12" title="<?php echo $this->__('Qty') ?>" class="input-text qty" onchange="setQty(<?php echo $_product->getId(); ?>, '<?php echo $this->getAddToCartUrl($_product) ?>');">
                                            <?php for ($k = 1; $k <= $_max; $k++) : ?>
                                                <option value="<?php echo $k ?>"><?php echo $k ?></option>
                                            <? endfor; ?>
                                        </select>
                                    </div>
                                    <div class="btn-cart" id="cart_button_<?php echo $_product->getId(); ?>"><button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button></div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

					<div class="product-name-box">
	                    <div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getData('title'); ?>
	                            <span><?php echo $_product->getData('sub_title'); ?></span></a>
	                    </div>
	
	                    <div class="product-price"><?php echo $this->getPriceHtml($_product, true) ?></div>
					</div>
                </li>
            </ul>
            <!-- END PRODUCT SPOTLIGHT HTML -->
            <?php $spotlit = 1; ?>
        <?php } else { ?>
                <?php if ($i++%$_columnCount==0): ?>
                    <ul class="products-grid">
                <?php endif ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="prod-grid-thumb">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" width="300" height="300" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                        <div class="prod-grid-content">
                            <div class="prod-grid-content-inner actions">

                                <div class="button btn-view"><a class="button" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span><span><?php echo $this->__('View Detail') ?></span></span></a></div>

                                <div class="button btn-quickview"><a class="button fancybox" data-fancybox-type="iframe" href="<?php echo Mage::getUrl('quickview/product/view/id/' . $_product->getId()); ?>"><span><span><?php echo $this->__('Quick View') ?></span></span></a></div>
                                <?php if($_product->isSaleable()): ?>
                                    <div class="qty-holder">
                                        <span><?php echo $this->__('Qty'); ?><?php echo $this->getMinimalQty($_product) ?></span>
                                        <?php
                                        $_max = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getMaxSaleQty();
                                        ?>
                                        <script type="text/javascript">
                                            function setQty(id, url) {
                                                var qty = document.getElementById('qty_' + id).value;
                                                if (url.substring(url.length-1) == '/') {
                                                    document.getElementById('cart_button_' + id).innerHTML = '<button type="button" class="button" onclick="setLocation(\'' + url + 'qty/' + qty + '/\')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button>';
                                                }
                                            }
                                        </script>
                                        <select name="qty_<?php echo $_product->getId() ?>" id="qty_<?php echo $_product->getId() ?>" maxlength="12" title="<?php echo $this->__('Qty') ?>" class="input-text qty" onchange="setQty(<?php echo $_product->getId(); ?>, '<?php echo $this->getAddToCartUrl($_product) ?>');">
                                            <?php for ($k = 1; $k <= $_max; $k++) : ?>
                                                <option value="<?php echo $k ?>"><?php echo $k ?></option>
                                            <? endfor; ?>
                                        </select>
                                    </div>
                                    <div class="btn-cart" id="cart_button_<?php echo $_product->getId(); ?>"><button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button></div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>


                    <div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getData('title'); ?>
                            <span><?php echo $_product->getData('sub_title'); ?></span></a>
                    </div>

                    <div class="product-price"><?php echo $this->getPriceHtml($_product, true) ?></div>

                </li>
                <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php } ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <div class="ad-bottom clearfix"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('ultimate-kate-rewards')->toHtml(); ?></div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery(".fancybox").fancybox({
                padding: 10,
                helpers: {
                    overlay: {
                        locked: false
                    }
                },
                maxWidth	: 980,
                maxHeight	: 800,
                fitToView	: false,
                width		: '70%',
                height		: '90%',
                autoSize	: false,
                closeClick	: false,
                openEffect	: 'none',
                closeEffect	: 'none'
            });
        });
    </script>
<?php endif; ?>
