<?php
// prep variables as needed

// strip background image to just image path
if (Mage::getModel('cms/block')->load('sweepstakes_module_bkgd')->getIsActive()) { 
	$bkgd = $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_bkgd')->toHtml();
	$bkgdArray = array();
	preg_match( '/src="([^"]*)"/i', $bkgd, $bkgdArray );
	$bkgdUrl = $bkgdArray[1];
	
}

// strip p tags from share URL
if (Mage::getModel('cms/block')->load('sweepstakes_module_share_link_url')->getIsActive()) { 
	$st_url = $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_share_link_url')->toHtml();
	$st_url = strip_tags($st_url);
}

// strip p tags from share title
if (Mage::getModel('cms/block')->load('sweepstakes_module_share_title')->getIsActive()) { 
	$st_title = $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_share_title')->toHtml();
	$st_title = strip_tags($st_title);
}

// strip share image to just image path
if (Mage::getModel('cms/block')->load('sweepstakes_module_share_img_url')->getIsActive()) { 
	$img = $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_share_img_url')->toHtml();
	$imgArray = array();
	preg_match( '/src="([^"]*)"/i', $img, $imgArray );
	$st_image = $imgArray[1];
}
?>
                
<!DOCTYPE html>
<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
    <div id="katesomerville" class="wrapper" data-role="page">
        <header data-role="header">
            <?php echo $this->getChildHtml('header'); ?>
        </header>
        
        <div id="sweepstakes-main" class="sweepstakes-thankyou">
            <?php echo $this->getLayout()->createBlock('alliance_globalbanner/globalBanner')->setTemplate('alliance/globalbanner/globalbanner.phtml')->setBlockId('alliance-globalbanner-globalbanner')->toHtml(); ?>
        	<?php echo $this->getChildHtml('global_messages') ?>
			 <div class="col-main" style="background-image: url(<?php echo $bkgdUrl; ?>);">
                
					
                <div id="sweepstakes-container">
                <div id="sweepstakes-container-inner">
                
                	<?php if (Mage::getModel('cms/block')->load('sweepstakes_module_cobranded_logo')->getIsActive()) { ?> 
                	<div class="sweepstakes-logo">
                		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_cobranded_logo')->toHtml(); ?>
                	</div>
                	<?php } ?>
                	
                	<div id="sweepstakes-thankyou-container">
                		<div id="sweepstakes-thankyou-inner">
							<?php if (Mage::getModel('cms/block')->load('sweepstakes_module_ksv_logo')->getIsActive()) { ?> 
			            	<div id="sweepstakes-katelogo">
			            		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_ksv_logo')->toHtml(); ?>
			            	</div>
			            	<?php } ?>
			            	
			            	
			            	<div id="sweepstakes-thankyou-intro">
								<?php if (Mage::getModel('cms/block')->load('sweepstakes_module_thankyou_hdr')->getIsActive()) { ?><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_thankyou_hdr')->toHtml(); ?><?php } ?>
								
								<div id="sweepstakes-share">
									<p>Share</p>
									<div class="social-icons">
										<span class='st_facebook' displayText='Facebook' st_url='<?php echo $st_url; ?>'
											  st_title='<?php echo $st_title; ?>'
											  st_image='<?php echo $st_image ?>'></span>
						                <span class='st_twitter' displayText='Tweet' st_url='<?php echo $st_url;?>'
											  st_title='<?php echo $st_title; ?>'
											  st_image='<?php echo $st_image ?>'></span>
						                <span class='st_pinterest' displayText='Pinterest' st_url='<?php echo $st_url; ?>'
											  st_title='<?php echo $st_title; ?>'
											  st_image='<?php echo $st_image ?>'></span>
						                <span class='st_googleplus' displayText='Google +' st_url='<?php echo $st_url; ?>'
											  st_title='<?php echo $st_title; ?>'
											  st_image='<?php echo $st_image ?>'></span>
					  				</div>
									
									<?php if (Mage::getModel('cms/block')->load('sweepstakes_module_share_hashtag')->getIsActive()) { ?><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_share_hashtag')->toHtml(); ?><?php } ?>
									
								</div><!-- end #sweepstakes-share -->
							</div><!-- end #sweepstakes-thankyou-intro -->
							
						</div><!-- end #sweepstakes-thankyou-inner -->
					</div><!-- end #sweepstakes-thankyou-container -->
                	                
                </div><!-- end #sweepstakes-inner -->
				</div><!-- end #sweepstakes-container -->
				                   
            </div><!-- end #sweepstakes-main -->
            
            <div id="sweepstakes-thankyou-bottom">
				
				<div class="left">
					<?php if (Mage::getModel('cms/block')->load('sweepstakes_module_thankyou_bottom_left')->getIsActive()) { echo $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_thankyou_bottom_left')->toHtml(); } ?>
				</div>
				
				<div class="right">
					<?php if (Mage::getModel('cms/block')->load('sweepstakes_module_thankyou_bottom_right')->getIsActive()) { echo $this->getLayout()->createBlock('cms/block')->setBlockId('sweepstakes_module_thankyou_bottom_right')->toHtml(); } ?>
				</div>
				
			</div><!-- end #sweepstakes-ageisjustanumber -->
			
        </div>
            
		<footer data-role="footer">
            <?php echo $this->getChildHtml('footer'); ?>
        </footer>
    </div>

</body>
</html>
