<?php $email = urldecode(Mage::app()->getRequest()->getParam('email')); ?>
Thank You!<br>
Your email address has been unsubscribed and will be removed from our marketing list within the next 1-2 business days.
<img src="http://e.katesomerville.com/public/?q=direct_unsub&fn=Public_DirectUnsubForm&id=aspgsqyqglchlwoagapkpdbfuzbkbea&email=<?php echo $email ?>" width="0" height="0" border="0" alt=""/>