<?php if($confirmed) {?>
<div class="giveawayfb-container giveawayfb-emailverification">
	<h1>Your samples are<br/>on their way</h1>
	<p>Thank you for your order.<br/>Please allow up to 15 business days to receive your samples in the mail.<br/>We hope you enjoy!</p>
	
	<div class="giveawayfb-socials"><ul>
		<li>Share with your friends:</li>
		<li><a href="http://www.facebook.com/share.php?u=<?php echo $moduleURL?>" rel="external"><img src="<?php echo $this->getSkinUrl('images/giveawayfb/social-facebook.png');?>" alt="" /></a></li><li><a href="http://twitter.com/home/?status=<?php echo $moduleDescription;?>%20:%20<?php echo $moduleURL?>" rel="external"><img src="<?php echo $this->getSkinUrl('images/giveawayfb/social-twitter.png');?>" alt="" /></a></li><li><a href="http://pinterest.com/pin/create/button/?url=<?php echo $moduleURL?>&media=<?php echo $this->getSkinUrl('images/giveawayfb/samples.jpg');?>&description=<?php echo $moduleDescription;?>" rel="external"><img src="<?php echo $this->getSkinUrl('images/giveawayfb/social-pinterest.png');?>" alt="" /></a></li>
	</ul></div>
</div>

<!-- Facebook Conversion Code for KS NL Sign-ups -->
<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6014472199202';
fb_param.value = '0.01';
fb_param.currency = 'USD';
(function(){
var fpw = document.createElement('script');
fpw.async = true;
fpw.src = '//connect.facebook.net/en_US/fp.js';
var ref = document.getElementsByTagName('script')[0];
ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6014472199202&value=0.01&currency=USD"; /></noscript>
<?php } else {?>
Sorry...
<?php }?>
