<?php 
/**
 * StoreFront Authorize.Net CIM Tokenized Payment Extension
 *
 * This source file is subject to commercial source code license of StoreFront Consulting, Inc.
 *
 * @category	SFC
 * @package    	SFC_AuthnetToken
 * @author      Garth Brantley
 * @website 	http://www.storefrontconsulting.com/
 * @copyright 	Copyright (C) 2009-2013 StoreFront Consulting, Inc. All Rights Reserved.
 * @license     http://www.storefrontconsulting.com/media/downloads/ExtensionLicense.pdf StoreFront Consulting Commercial License
 *
 */
?>
<?php $paymentProfiles = $this->getPaymentProfiles() ?>
<div class="page-title">
    <h1>My Credit Cards</h1>
</div>

<fieldset>
	<div class="pager">
		<p class="amount">
			<?php echo count($paymentProfiles); ?> Item(s)
		</p>
	</div>
	<table class="data-table" id="cc-table">
		<thead>
			<tr class="first last">
				<th>Card Number</th>
				<th>Billing Customer Name</th>
				<th>Edit / Delete</th>
			</tr>
		</thead>
		<tbody>
			<?php $i= 0; ?>
			<?php foreach($paymentProfiles as $profile) : ?>
			<?php if($i % 2 == 0) { $row = 'even'; } else { $row='odd'; } ?>
			<tr class="<?php echo $row; ?>">
				<td>
					<?php $card = str_repeat('x', (strlen($profile->getCustomerCardnumber()) - 4)) . substr($profile->getCustomerCardnumber(),-4,4); ?>
					<?php echo $card ?>
				</td>
				<td>
					<?php echo $profile->getCustomerFname().' '.$profile->getCustomerLname(); ?>
				</td>
				<td>
					<span><a href="<?php echo Mage::getUrl('creditcards/index/edit'); ?>id/<?php echo $profile->getId() ?>"><b>Edit</b></a></span> |
					<span><a href="#" class="link-reorder" onclick="confirmDelete(<?php echo $profile->getId() ?>)"> Delete</a></span>
				</td>
			</tr>
			<?php $i++; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	<div class="pager">
		<p class="amount">
			<?php echo count($paymentProfiles); ?> Item(s)
		</p>
	</div>
</fieldset>

<br/>

<div class="buttons-set form-buttons">
	<p class="back-link"><a href="<?php echo Mage::getUrl('customer/account/'); ?>"><small>&#171;</small> Back</a></p>
	<button type="submit" class="button" title="Save" onclick="window.location.href='<?php echo Mage::getUrl('creditcards/index/new'); ?>customerid/<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId() ?>'">
		<span><span>New Credit Card</span></span>
	</button>
</div>
<script type="text/javascript">
function confirmDelete(id)
{
    var x;
    var r=confirm("Are you sure you want to delete this credit card?");
    if (r==true)
    {
        window.location="<?php echo Mage::getUrl('creditcards/index/delete'); ?>id/" + id;
    }
    else
    {
        return false;
    }
}
</script>





